name: dart_mcp_examples
description: Examples for the Dart MCP package.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.7.0
  async: ^2.13.0
  cli_util: ^0.4.2
  dart_mcp: ^0.2.0
  google_generative_ai: ^0.4.7
  path: ^1.9.1
  stream_channel: ^2.1.4

dependency_overrides:
  dart_mcp:
    path: ../pkgs/dart_mcp
