name: dev_mcp_host
description: "A DevTools extension for local MCP server development"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.8.0-261.0.dev

dependencies:
  flutter:
    sdk: flutter

  devtools_extensions: ^0.3.1
  devtools_app_shared: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
