# Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

# Configuration for .github/workflows/pull_request_label.yml.

'type-infra':
  - changed-files:
    - any-glob-to-any-file: '.github/**'

'package:dart_mcp':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/dart_mcp/**'

'package:dart_mcp_server':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/dart_mcp_server/**'
