name: counter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0-wip

# As this is a flutter project we exclude it from the workspace.
# This avoids making flutter SDK a dependency during development.
# resolution: workspace
environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  dart_flutter_team_lints: ^3.2.1

  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
