name: dart_tooling_mcp_server
publish_to: none
version: 0.1.0-wip
environment:
  sdk: ^3.7.0
dependencies:
  async: ^2.13.0
  dart_mcp:
    path: ../dart_mcp
  dtd: ^2.4.0
  json_rpc_2: ^3.0.3
  stream_channel: ^2.1.4
  vm_service: ^15.0.0
executables:
  dart_tooling_mcp_server: main
dev_dependencies:
  dart_flutter_team_lints: ^3.5.1
  test: ^1.25.15
