name: dart_tooling_mcp_server
description: An MCP server for Dart projects, exposing various developer tools to AI models.
publish_to: none
version: 0.1.0-wip
environment:
  sdk: ^3.7.0 # The version of dart in the current flutter stable
dependencies:
  async: ^2.13.0
  dart_mcp: ^2.0.0
  dds_service_extensions: ^2.0.1
  devtools_shared: ^11.2.0
  dtd: ^2.4.0
  json_rpc_2: ^3.0.3
  # TODO: Get this another way.
  language_server_protocol:
    git:
      url: https://github.com/dart-lang/sdk.git
      path:
        third_party/pkg/language_server_protocol
  meta: ^1.16.0
  path: ^1.9.1
  process: ^5.0.3
  stream_channel: ^2.1.4
  test_descriptor: ^2.0.2
  test_process: ^2.1.1
  vm_service: ^15.0.0
executables:
  dart_tooling_mcp_server: main
dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  test: ^1.25.15

dependency_overrides:
  dart_mcp:
    path: ../dart_mcp
