name: mcp_codegen
version: 0.1.0-wip
publish_to: none
description: >-
  Source-gen builder that generates boilerplate MCP server and tool code.

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: ^6.4.0
  build: ^2.4.0
  source_gen: ^1.5.0
  dart_mcp:
    path: ../dart_mcp
  mcp_annotations:
    path: ../mcp_annotations  
  meta: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.2 

