name: dart_mcp_server
description: >-
  An MCP server for Dart projects, exposing various developer tools to AI
  models.
publish_to: none
environment:
  sdk: ^3.7.0

executables:
  dart_mcp_server: main

dependencies:
  args: ^2.7.0
  async: ^2.13.0
  collection: ^1.19.1
  dart_mcp: ^0.2.2
  dds_service_extensions: ^2.0.1
  devtools_shared: ^11.2.0
  dtd: ^2.4.0
  file: ^7.0.1
  http: ^1.3.0
  json_rpc_2: ^3.0.3
  # TODO: Get this another way.
  language_server_protocol:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: third_party/pkg/language_server_protocol
  meta: ^1.16.0
  path: ^1.9.1
  pool: ^1.5.1
  process: ^5.0.3
  stream_channel: ^2.1.4
  unified_analytics: ^8.0.2
  vm_service: ^15.0.0
  watcher: ^1.1.1
  web_socket: ^1.0.1
  yaml: ^3.1.3

dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  test: ^1.25.15
  test_descriptor: ^2.0.2
  test_process: ^2.1.1

dependency_overrides:
  dart_mcp:
    path: ../dart_mcp
