name: dart_mcp
description: A package for making MCP servers and clients.
version: 0.1.0-wip
environment:
  sdk: ^3.6.1 # The version of dart in the current flutter stable
dependencies:
  async: ^2.13.0
  json_rpc_2: ^3.0.3
  meta: ^1.16.0
  stream_channel: ^2.1.4
executables:
  dart_mcp_server: server
dev_dependencies:
  dart_flutter_team_lints: ^3.2.1
  test: ^1.25.15
