name: dart_mcp
description: A package for making MCP servers and clients.
repository: https://github.com/dart-lang/ai/tree/main/pkgs/dart_mcp
version: 0.2.0-wip
environment:
  sdk: ^3.7.0
dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  json_rpc_2: ^3.0.3
  meta: ^1.16.0
  stream_channel: ^2.1.4
dev_dependencies:
  args: ^2.7.0
  dart_flutter_team_lints: ^3.2.1
  google_generative_ai: ^0.4.6
  test: ^1.25.15
