name: Health
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@main
    with:
      checks: "version,changelog,do-not-submit,breaking"
      flutter_packages: "pkgs/dart_tooling_mcp_server/test_fixtures/counter_app"
      sdk: dev
    permissions:
      pull-requests: write
